seek_duration_secs = 10
modal_search = true
client_id_command = { command = "cat", args = [
  "/run/secrets/spotify_client_id",
] }

theme = "dracula"
client_port = 8080
playback_format = """
{status} {track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
enable_streaming = "DaemonOnly"
enable_notify = false
enable_cover_image_cache = true
default_device = "spotify-player"

[layout]
playback_window_position = "Bottom"
playback_window_height = 6

[layout.library]
playlist_percent = 40
album_percent = 40

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
normalization = false
autoplay = false
