# newline printing should be handled by zsh precmd
add_newline = false

format = """
$directory$git_branch$git_status$cmd_duration$fill$nix_shell${custom.context}$time
$character"""

# Spacing in between prompt parts
[fill]
symbol =" "

[character]
success_symbol = "[;](purple)"
error_symbol = "[;](red)"
vicmd_symbol = "[:](white)"

# Modules
[cmd_duration]
min_time = 500
format = "[took $duration](bright-black)"

[directory]
style = "blue"
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"
disabled = false


[git_branch]
format = " [$symbol$branch](green) "
symbol = "" # 

[nix_shell]
symbol = ''
format = '[$symbol $state](blue) '

[git_status]
format = '([$all_status$ahead_behind]($style))'
disabled = true

[custom.context]
command = 'echo $USER@$(hostname)'
when = ''' [[ -v SSH_TTY || -v SSH_CLIENT ]] '''
format = '[with $output](dimmed white)'

[time]
disabled = true
use_12hr = true
style = "bright-black"
format = "[$time]($style)"
