gui:
  screenMode: 'normal' # one of 'normal' | 'half' | 'full' default is 'normal'
  scrollHeight: 2 # how many lines you scroll by
  scrollPastBottom: true # enable scrolling past the bottom
  scrollOffMargin: 2 # how many lines to keep before/after the cursor when it reaches the top/bottom of the view; see 'Scroll-off Margin' section below
  scrollOffBehavior: 'margin' # one of 'margin' | 'jump'; see 'Scroll-off Margin' section below
  sidePanelWidth: 0.3333 # number from 0 to 1
  expandFocusedSidePanel: false
  mainPanelSplitMode: 'flexible' # one of 'horizontal' | 'flexible' | 'vertical'
  language: 'en'
  timeFormat: '02 Jan 06'
  shortTimeFormat: '3:04PM'
  commitLength:
    show: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showFileTree: true 
  showListFooter: true 
  showRandomTip: false
  showBranchCommitHash: false 
  showBottomLine: false
  showPanelJumps: false 
  showCommandLog: false
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  splitDiff: 'auto' 
  skipRewordInEditorWarning: true # for skipping the confirmation before launching the reword editor
  border: 'rounded' # one of 'single' | 'double' | 'rounded' | 'hidden'
  portraitMode: 'auto' # one of 'auto' | 'never' | 'always'

git:
  skipHookPrefix: WIP
  mainBranches: [master, main]
  autoFetch: false
  autoRefresh: true
  fetchAll: true
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium'
  disableForcePushing: false
  parseEmoji: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  commit:
    signOff: false
  merging:
    manualCommit: false
    args: ''

refresher:
  refreshInterval: 10 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
  fetchInterval: 60 # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.

update:
  method: prompt # can be: prompt | background | never
  days: 14 # how often an update is checked for

confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: false
notARepository: 'prompt' # one of: 'prompt' | 'create' | 'skip' | 'quit'
promptToReturnFromSubprocess: true # display confirmation when subprocess terminates

customCommands:
  - key: "s"
    context: "files"
    command: "git stash -u -- {{.SelectedFile.Name | quote}}"
