# this file was generated by nixpins (https://github.com/juliamertz/nixpins)
{fetchFromGitHub, ...}: let
  fetchFlake = attrs: builtins.getFlake "${attrs.url}/${attrs.rev}";
in {
  inputs = {
    godoc.url = "github:fredrikaverpil/godoc.nvim";
    nixcats.url = "github:BirdeeHub/nixCats-nvim";
    noogle = {
      url = "github:juliamertz/noogle-cli";
      flake = true;
    };
    rose-pine.url = "github:rose-pine/neovim";
    snacks.url = "github:folke/snacks.nvim";
  };
  sources = {
    godoc = fetchFromGitHub {
      owner = "fredrikaverpil";
      repo = "godoc.nvim";
      rev = "356f79853dbb3b3e200064367603751895153c29";
      hash = "sha256-w5NP/Hb7e/ZROVvc5+C0xxz4ecnWPdo6ICaCPlpaWhs=";
    };
    nixcats = fetchFromGitHub {
      owner = "BirdeeHub";
      repo = "nixCats-nvim";
      rev = "c0148957e961100bff3fd213b8a4bc5f669f3028";
      hash = "sha256-3T2Yl+xSnx7snXZkMaQNHCvlj0CB+lyAj+Q/+eeh+Ns=";
    };
    noogle = fetchFlake {
      url = "github:juliamertz/noogle-cli";
      rev = "14b9e7d15bf46f9168690fdb17dd34193034e427";
      hash = "sha256-pYOfnNUMfJBFF7Ri07BNZfxoYtgWuqWUTEROdqeaGUA=";
    };
    rose-pine = fetchFromGitHub {
      owner = "rose-pine";
      repo = "neovim";
      rev = "6b9840790cc7acdfadde07f308d34b62dd9cc675";
      hash = "sha256-o3uAO/PrNsNIyZrHKy0WCwJNd9C/TAC3QVcxPapFxAE=";
    };
    snacks = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      hash = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
  };
}
