# this file was generated by nixpins (https://github.com/juliamertz/nixpins)
{fetchFromGitHub, ...}: let
  fetchFlake = attrs: builtins.getFlake "${attrs.url}/${attrs.rev}";
in {
  inputs = {
    godoc.url = "github:fredrikaverpil/godoc.nvim";
    nixcats.url = "github:BirdeeHub/nixCats-nvim";
    noogle = {
      url = "github:juliamertz/noogle-cli";
      flake = true;
    };
    rose-pine.url = "github:rose-pine/neovim";
    snacks.url = "github:folke/snacks.nvim";
  };
  sources = {
    godoc = fetchFromGitHub {
      owner = "fredrikaverpil";
      repo = "godoc.nvim";
      rev = "356f79853dbb3b3e200064367603751895153c29";
      hash = "sha256-w5NP/Hb7e/ZROVvc5+C0xxz4ecnWPdo6ICaCPlpaWhs=";
    };
    nixcats = fetchFromGitHub {
      owner = "BirdeeHub";
      repo = "nixCats-nvim";
      rev = "a985eb3e7d30d3f9c9cf7e8a8718d2d10126bcbd";
      hash = "sha256-Bj8RGeMMNT4MThQJaKjML123kTXiKtTPsXWC2ieaiDc=";
    };
    noogle = fetchFlake {
      url = "github:juliamertz/noogle-cli";
      rev = "14b9e7d15bf46f9168690fdb17dd34193034e427";
      hash = "sha256-pYOfnNUMfJBFF7Ri07BNZfxoYtgWuqWUTEROdqeaGUA=";
    };
    rose-pine = fetchFromGitHub {
      owner = "rose-pine";
      repo = "neovim";
      rev = "f93360149e9ed4df8677fbb07c7231ea0fd03b97";
      hash = "sha256-bf47ECpuUBtcFdJRhTH9GxjERQyf0CayZjP7V6+WL5k=";
    };
    snacks = fetchFromGitHub {
      owner = "folke";
      repo = "snacks.nvim";
      rev = "bc0630e43be5699bb94dadc302c0d21615421d93";
      hash = "sha256-Gw0Bp2YeoESiBLs3NPnqke3xwEjuiQDDU1CPofrhtig=";
    };
  };
}
