#!/usr/bin/env sh

url="$1"
browser=${TEXT_BROWSER:-""}

if ! test -n "$browser"; then
  if command -v w3m >/dev/null; then browser=$(which w3m);
  elif command -v lynx >/dev/null; then browser=$(which lynx);
  elif test -n "$BROWSER"; then browser=$BROWSER;
  else 
    echo No suitable browser found, exiting...
    exit 1
  fi
fi

$browser "$url"
