#!/bin/sh

REMOTES=$(cat ~/.config/.sharedsecrets | jq .remotes)
TARGET_REMOTE=$(echo $REMOTES | jq ".$1")

HOST=$(echo $TARGET_REMOTE | jq .host | xargs)
USER=$(echo $TARGET_REMOTE | jq .user | xargs)

if [[ $TERM == "xterm-kitty" ]]; then
  kitty +kitten ssh $HOST -l $USER
else
  ssh $HOST -l $USER
fi

