# this file was generated by nixpins: https://github.com/juliamertz/nixpins
{fetchFromGitHub, ...}: {
  inputs = {
    ez-compinit.url = "github:mattmc3/ez-compinit";
    fzf-tab.url = "github:Aloxaf/fzf-tab";
    zsh-autocomplete.url = "github:marlonrichert/zsh-autocomplete";
    zsh-autosuggestions.url = "github:zsh-users/zsh-autosuggestions";
    zsh-completions.url = "github:zsh-users/zsh-completions";
    zsh-syntax-highlighting.url = "github:zsh-users/zsh-syntax-highlighting";
    zsh-vi-mode.url = "github:jeffreytse/zsh-vi-mode";
  };
  sources = {
    ez-compinit = fetchFromGitHub {
      owner = "mattmc3";
      repo = "ez-compinit";
      rev = "5c9b6da88a463573e26e6846ff164026640ef2f6";
      hash = "sha256-j/HF2hwBHvNNQpXSyEswCLZIPk8Ee+goB8fC3FALqgo=";
    };
    fzf-tab = fetchFromGitHub {
      owner = "Aloxaf";
      repo = "fzf-tab";
      rev = "cbdc58226a696688d08eae63d8e44f4b230fa3dd";
      hash = "sha256-ZekrZYQBGYQOTMojnJbQhelH4rOyzuPIP/Tu/6Tjwec=";
    };
    zsh-autocomplete = fetchFromGitHub {
      owner = "marlonrichert";
      repo = "zsh-autocomplete";
      rev = "bbba73ebdc7c01323e09d4d518e51e2d6847ccc2";
      hash = "sha256-998rYEyYD67XleSDbqvnQptRrGuG2N2AgFvTpFWvoV8=";
    };
    zsh-autosuggestions = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-autosuggestions";
      rev = "85919cd1ffa7d2d5412f6d3fe437ebdbeeec4fc5";
      hash = "sha256-KmkXgK1J6iAyb1FtF/gOa0adUnh1pgFsgQOUnNngBaE=";
    };
    zsh-completions = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-completions";
      rev = "7dd26c5d5c3fabd630b748bd49ebd9cf02bd57e9";
      hash = "sha256-ICr/nBxnoDGp/22J5W1npPw8N/Ryc3gs32dC6fpk1CA=";
    };
    zsh-syntax-highlighting = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "5eb677bb0fa9a3e60f0eff031dc13926e093df92";
      hash = "sha256-KRsQEDRsJdF7LGOMTZuqfbW6xdV5S38wlgdcCM98Y/Q=";
    };
    zsh-vi-mode = fetchFromGitHub {
      owner = "jeffreytse";
      repo = "zsh-vi-mode";
      rev = "08bd1c04520418faee2b9d1afbc410ee1a59a8f1";
      hash = "sha256-WdZHCVxVVOs4HyG5f56vAA17UWYOvb9Yf6v7M1RIdU4=";
    };
  };
}
