# this file was generated by nixpins (https://github.com/juliamertz/nixpins)
{ fetchFromGitHub, ... }:
{
  inputs = {
    fzf-tab = "github:Aloxaf/fzf-tab";
    zsh-autosuggestions = "github:zsh-users/zsh-autosuggestions";
    zsh-completions = "github:zsh-users/zsh-completions";
    zsh-syntax-highlighting = "github:zsh-users/zsh-syntax-highlighting";
    zsh-vi-mode = "github:jeffreytse/zsh-vi-mode";
  };
  sources = {
    fzf-tab = fetchFromGitHub {
      owner = "Aloxaf";
      repo = "fzf-tab";
      rev = "01dad759c4466600b639b442ca24aebd5178e799";
      hash = "sha256-q26XVS/LcyZPRqDNwKKA9exgBByE0muyuNb0Bbar2lY=";
    };
    zsh-autosuggestions = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-autosuggestions";
      rev = "0e810e5afa27acbd074398eefbe28d13005dbc15";
      hash = "sha256-85aw9OM2pQPsWklXjuNOzp9El1MsNb+cIiZQVHUzBnk=";
    };
    zsh-completions = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-completions";
      rev = "e61c9c14d6978191762e9586a0c882114e49221d";
      hash = "sha256-9s9EkorKNH1DrA9rKUl/4aGIZY+7+EyryZ/69365te0=";
    };
    zsh-syntax-highlighting = fetchFromGitHub {
      owner = "zsh-users";
      repo = "zsh-syntax-highlighting";
      rev = "5eb677bb0fa9a3e60f0eff031dc13926e093df92";
      hash = "sha256-KRsQEDRsJdF7LGOMTZuqfbW6xdV5S38wlgdcCM98Y/Q=";
    };
    zsh-vi-mode = fetchFromGitHub {
      owner = "jeffreytse";
      repo = "zsh-vi-mode";
      rev = "cd730cd347dcc0d8ce1697f67714a90f07da26ed";
      hash = "sha256-UQo9shimLaLp68U3EcsjcxokJHOTGhOjDw4XDx6ggF4=";
    };
  };
}
