# this file was generated by nixpins: https://github.com/juliamertz/nixpins
{fetchFromGitHub, ...}: {
  inputs = {
    rose-pine.url = "github:rose-pine/fish";
  };
  sources = {
    rose-pine = fetchFromGitHub {
      owner = "rose-pine";
      repo = "fish";
      rev = "6cfc508e81b231e955690dc9723c631374f468eb";
      hash = "sha256-NgfZnaik5OAur53y3WA0Hqu6f332aVdhhMWnEtDxmNs=";
    };
  };
}
