# this file was generated by nixpins (https://github.com/juliamertz/nixpins)
{fetchFromGitHub, ...}: {
  inputs = {
    rose-pine.url = "github:rose-pine/fish";
  };
  sources = {
    rose-pine = fetchFromGitHub {
      owner = "rose-pine";
      repo = "fish";
      rev = "b82982c55582cfaf6f220de1893c7c73dd0cb301";
      hash = "sha256-Dvaw1k7XOU2NUQbTJAXPgAOPN1zTLVrc7NZDY5/KHeM=";
    };
  };
}
