# this file was generated by nixpins: https://github.com/juliamertz/nixpins
{ fetchFromGitHub, ... }:
{
  inputs = {
    rose-pine.url = "github:rose-pine/fish";
  };
  sources = {
    rose-pine = fetchFromGitHub {
      owner = "rose-pine";
      repo = "fish";
      rev = "0749331afd4be6bc8035a812a20e489efe1d616f";
      hash = "sha256-hOcsGt0IMoX1a02t85qeoE381XEca0F2x0AtFNwOqj0=";
    };
  };
}
